#sh run_batch_Genome_Ontology.sh mm9 REAL
#sh run_batch_Genome_Ontology.sh mm9 Cerebellum_H3_nuc_background_RANDOMS_250
#sh run_batch_Genome_Ontology.sh mm9 Heart_H3_nuc_background_RANDOMS_250
#sh run_batch_Genome_Ontology.sh mm9 Liver_H3_nuc_background_RANDOMS_250
#sh run_batch_Genome_Ontology.sh mm9 NPCs_H3_nuc_background_RANDOMS_250
#sh run_batch_Genome_Ontology.sh mm9 OlfactoryBulb_H3_nuc_background_RANDOMS_250




parse_HOMER_GO.pl 2019-11-04_HOMER_GenOnt_Randomizations_OlfactoryBulb_H3Nuc_LOST.txt ./REAL/GO_RAND/dposREF_OlfactoryBulb_DiNUP_DANPOS_LOST_basic_genomeOntology.txt ./OlfactoryBulb_H3_nuc_background_RANDOMS_250/GO_RAND
parse_HOMER_GO.pl 2019-11-04_HOMER_GenOnt_Randomizations_OlfactoryBulb_H3Nuc_GAIN.txt ./REAL/GO_RAND/dposREF_OlfactoryBulb_DiNUP_DANPOS_GAINED_basic_genomeOntology.txt ./OlfactoryBulb_H3_nuc_background_RANDOMS_250/GO_RAND
parse_HOMER_GO.pl 2019-11-04_HOMER_GenOnt_Randomizations_NPCs_H3Nuc_LOST.txt ./REAL/GO_RAND/dposREF_NPCs_DiNUP_DANPOS_LOST_basic_genomeOntology.txt ./NPCs_H3_nuc_background_RANDOMS_250/GO_RAND
parse_HOMER_GO.pl 2019-11-04_HOMER_GenOnt_Randomizations_NPCs_H3Nuc_GAIN.txt ./REAL/GO_RAND/dposREF_NPCs_DiNUP_DANPOS_GAINED_basic_genomeOntology.txt ./NPCs_H3_nuc_background_RANDOMS_250/GO_RAND
parse_HOMER_GO.pl 2019-11-04_HOMER_GenOnt_Randomizations_Liver_H3Nuc_LOST.txt ./REAL/GO_RAND/dposREF_Liver_DiNUP_DANPOS_LOST_basic_genomeOntology.txt ./Liver_H3_nuc_background_RANDOMS_250/GO_RAND
parse_HOMER_GO.pl 2019-11-04_HOMER_GenOnt_Randomizations_Liver_H3Nuc_GAIN.txt ./REAL/GO_RAND/dposREF_Liver_DiNUP_DANPOS_GAINED_basic_genomeOntology.txt ./Liver_H3_nuc_background_RANDOMS_250/GO_RAND
parse_HOMER_GO.pl 2019-11-04_HOMER_GenOnt_Randomizations_Heart_H3Nuc_LOST.txt ./REAL/GO_RAND/dposREF_Heart_DiNUP_DANPOS_LOST_basic_genomeOntology.txt ./Heart_H3_nuc_background_RANDOMS_250/GO_RAND
parse_HOMER_GO.pl 2019-11-04_HOMER_GenOnt_Randomizations_Heart_H3Nuc_GAIN.txt ./REAL/GO_RAND/dposREF_Heart_DiNUP_DANPOS_GAINED_basic_genomeOntology.txt ./Heart_H3_nuc_background_RANDOMS_250/GO_RAND
parse_HOMER_GO.pl 2019-11-04_HOMER_GenOnt_Randomizations_Cerebellum_H3Nuc_LOST.txt ./REAL/GO_RAND/dposREF_Cerebellum_DiNUP_DANPOS_LOST_basic_genomeOntology.txt ./Cerebellum_H3_nuc_background_RANDOMS_250/GO_RAND
parse_HOMER_GO.pl 2019-11-04_HOMER_GenOnt_Randomizations_Cerebellum_H3Nuc_GAIN.txt ./REAL/GO_RAND/dposREF_Cerebellum_DiNUP_DANPOS_GAINED_basic_genomeOntology.txt ./Cerebellum_H3_nuc_background_RANDOMS_250/GO_RAND
